Repository ucsb-cs156-s25/proj-courses-s25-03, pull requests merged in 2025-05, with the labels that each got.

#25 Added the enrollmentDataPointFixtures sample data.
  frontend/src/fixtures/enrollmentDataPointFixtures.js
Labels: 5, Merge Candidate-CI

#31 Add filter component for pagination of the Jobs frontend
  frontend/src/main/components/Jobs/JobsSearchForm.js
  frontend/src/stories/components/Jobs/JobsSearchForm.stories.js
  frontend/src/tests/components/Jobs/JobsSearchForm.test.js
Labels: 10

#41 Create fixtures for the GE area dropdown component
  frontend/src/fixtures/geAreaFixtures.js
Labels: 5

#29 Paginate the Jobs backend
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/repositories/JobsRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
Labels: 10

#39 xw - add endpoint to return array of GE Areas
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate-CI

#49 xw - refactor tests for CSV
  src/main/java/edu/ucsb/cs156/courses/controllers/CoursesCSVController.java
  src/main/java/edu/ucsb/cs156/courses/services/SectionCSVLineService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CoursesCSVControllerExceptionTests.java
  src/test/java/edu/ucsb/cs156/courses/controllers/CoursesCSVControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/SectionCSVLineServiceTests.java
Labels: 10, Merge Candidate-CI

#43 added placeholder and added routes for GESearch
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/GeneralEducation/GeneralEducationSearchPage.js
Labels: 5, Merge Candidate-CI

#58 KW - Create dropdown for classroom numbers
  frontend/src/main/components/Classrooms/SingleClassroomDropdown.js
  frontend/src/stories/components/Classrooms/SingleClassroomDropdown.stories.js
  frontend/src/tests/components/Classrooms/SingleClassroomDropdown.test.js
Labels: 10

#55 Change the enrollment history graph to use sample data provided by enrollmentDataPointFixtures
  frontend/src/fixtures/enrollmentDataPointFixtures.js
  frontend/src/main/components/EnrollmentData/EnrollmentHistoryGraph.js
  frontend/src/stories/components/EnrollmentData/EnrollmentHistoryGraph.stories.js
  frontend/src/tests/components/EnrollmentData/EnrollmentHistoryGraph.test.js
Labels: 10
